# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79100ceea1cdc911073ed3cb5196ac7d7e9f3f5f0d3477cf24f1fdd21cb7184279b812686a3e915270ff859abee993e74ca68ac5bbb5a102278a66ec8e4ca3f1
  linkedin_key: <%= ENV["LINKEDIN_KEY"] %>
  linkedin_secret: <%= ENV["LINKEDIN_SECRET"] %>
  mixpanel_key: <%= ENV["MIXPANEL_KEY"] %>

test:
  secret_key_base: 47016f89079237aa83db39e47eb56864427023f0a4438e3433295ea6c01c35862c301c18412eb835f1675cebebbfb62a93d62ef67fe910b11d0d32f79375870b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  linkedin_key: <%= ENV["LINKEDIN_KEY"] %>
  linkedin_secret: <%= ENV["LINKEDIN_SECRET"] %>
  mixpanel_key: <%= ENV["MIXPANEL_KEY"] %>
